import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Logo from "@/public/logo.png"; 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const menu = [
  {
    label: "Home",
    href: "/",
  },
  {
    label: "Analyze Profile",
    href: "/analyzeProfile",
  },
  {
    label: "Dashboard",
    href: "/dashboard",
  },
  {
    label: "How It Works?",
    href: "/work",
  },
  {
    label: "About ",
    href: "/about",
  }
];
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="flex cursor-pointer bg-gradient-to-r from-[#e6f7e6] to-[#daf5da] shadow-lg rounded-2xl top-1 left-[200px] sticky w-3/4 py-4 px-10 justify-between items-center border border-[#cfe9cf]">
      <Link href="/">
      <Image src={Logo} alt="Logo" width={60} height={20} className="h-auto object-contain" /> 
      </Link>

  <div className="flex gap-8 items-center text-gray-700">
    {menu.map((item, index) => (
      <Link href={item.href} key={index} className="hover:text-red-300 transition">
        {item.label}
      </Link>
    ))}
    <Link href="/login">
    <button className="border border-gray-400 text-gray-700 px-4 py-2 rounded-full  hover:bg-gray-100 transition">
    Login
    </button>
    </Link>

<Link href="/signup">
    <button className="cursor-pointer    bg-black text-white px-5 py-2 rounded-full hover:bg-gray-800 transition">
      Sign up
    </button>
    </Link>
  </div>
      </nav>
        <section>{children}</section>
        <footer className="bg-black text-white py-6">
      <div className="container mx-auto flex flex-col md:flex-row justify-between items-center px-4">
        
     
        <div className="text-lg font-bold">
          <Image src={Logo} alt="Logo" width={100} height={50} className="object-contain" />
        </div>

        
        <div className="flex space-x-6 text-sm mt-4 md:mt-0">
          <a href="/" className="hover:text-gray-400 transition">Home</a>
          <a href="/about" className="hover:text-gray-400 transition">About</a>
          <a href="/work" className="hover:text-gray-400 transition">How It Works?</a>
        
        </div>

   
        <div className="flex space-x-4 mt-4 md:mt-0">
          <a href="#" className="hover:text-gray-400 transition">FB</a>
          <a href="#" className="hover:text-gray-400 transition">TW</a>
          <a href="#" className="hover:text-gray-400 transition">IG</a>
        </div>

      </div>
    </footer>
      </body>
    </html>
  );
}
